language: ruby
rvm:
  - 2.6.3

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
install: gem install jekyll
script: jekyll build

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

exclude: [vendor]
    
cache: bundler # caching bundler gem packages will speed up build

notifications:
  email: false