# Site settings
title: Mundo Oceluna portfolio!
email: mundo.oceluna@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mundo Oceluna portfolio
baseurl:  # the subpath of your site, e.g. /blog/
#url: http://127.0.0.1:4000/ # the base hostname & protocol for your site
url: https://mundooceluna.github.io/
twitter_username: oceluna
github_username:  mundooceluna

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
#plugins: [jekyll-paginate]
#paginate: 15
#paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


